name: test, build and deploy infra
on: 
  pull_request:
    branches: [main]
env:
  PY_VERSION: 3.12.x

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}
          cache: 'pip' # caching pip dependencies 

      - name: Install dependencies
        run: pip install -r test/requirements.txt

      - name: Run unit test cases
        run: |
          cd test/unit 
          pytest 

  
  build-and-deploy-infra:
    needs: test-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build
        working-directory: aws-serverless-website
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: aws-serverless-website

    
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --size-only
        env:
          AWS_S3_BUCKET: hiten-cloud-resume
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'website'